### ISSUE TITLE
Problem with Debugger

### ISSUE THREAD

**Issue by EM-Finn** [rikka0w0/MobZReborn#10]
I created a build with another mod that allows you to spawn various items in the hands of mobs. Because of this, some mobs will spawn with a debugger in hand.
I tried using the sources to change the damage from 1997 to 1, however, the newly compiled file "net/mobz/item/weapon/DebugoMat.class" when replacing it inside the mod breaks the assembly itself
How can I change the damage of the debugger or even remove it from the game?

**Comment by rikka0w0** [comment]
I see. The most elegant way of doing this is to add a tag that specifies which items mobs cannot have in their hand (when they spawn). However, this requires consensus between mods. For now, I'm going to add an option in the config file so that you can completely remove the debug stick from the game.

**Comment by rikka0w0** [comment]
I had a look at this, the item registration nowadays has to be static (at least for Fabric), which means this happens before any configuration gets loaded and makes optional item registration impossible. I would recommend that you setup a blacklist (can be a hardcoded list or a vanilla Tag) and add those items that are supposed not to be carried by mobs to it.
