### ISSUE TITLE
Raids broken

### ISSUE THREAD

**Issue by beautiful-lunatic** [rikka0w0/MobZReborn#5]
Hi! I am using the newest version of this mod, and it seems to completely mess up raids. Taking the mod out lets me complete raids like normal.

I've seen (Bowman) spawn with a banner before so i don't know if the game sees it as an illager, but even going into spectator and killing all the mobz mobs in the area of a raid in the caves still seems to screw things over..

**Comment by rikka0w0** [comment]
Hi,

This problem is known and it exists since I took over the development. I assume you are using the 1.17.1 version, by the time of the release of that version, Forge did not re-add the support for mixin, and I cannot implement one important patch which prevents the underground illagers to join the raid.



> I've seen (Bowman) spawn with a banner before so i don't know if the game sees it as an illager, but even going into spectator and killing all the mobz mobs in the area of a raid in the caves still seems to screw things over..

You are correct. The bowman, knight, and dwarf are based on the illager base class. I'm aware of this issue, but fixing it would need a total rewrite of their code. Currently, I don't have time to do so, but it seems that Forge now supports mixin again and I can create another patch mod that prevents creatures underground from joining the raid.

Regards,

Rikka0w0
